---
title: "Assignment_2"
author: "Aarush Bhardwaj"
date: "10/2/2021"
output: pdf_document
---

```{r}
library(lpSolveAPI)

setwd("~/Documents/Quant Assignment 2/Quant_assigment2")
```

```{r}
# make an lp object with 0 constraints and 9 decision variables
lprec <- make.lp(0, 9)
lprec

# Create the objective function and since we need to maximize profit, change the sense to max.
set.objfn(lprec, c(420, 360, 300, 420, 360, 300, 420, 360, 300))
lp.control(lprec,sense='max')

# Add the constraints
add.constraint(lprec, c(1, 1, 1, 0, 0, 0, 0, 0, 0), "<=", 750)
add.constraint(lprec, c(0, 0, 0, 1, 1, 1, 0, 0, 0), "<=", 900)
add.constraint(lprec, c(0, 0, 0, 0, 0, 0,1, 1, 1), "<=", 450)
add.constraint(lprec, c(20, 15, 12, 0, 0, 0, 0, 0, 0), "<=", 13000)
add.constraint(lprec, c(0, 0, 0, 20, 15, 12, 0, 0, 0), "<=", 12000)
add.constraint(lprec, c(0, 0, 0, 0, 0, 0, 20, 15, 12), "<=", 5000)
add.constraint(lprec, c(1, 1, 1, 0, 0, 0, 0, 0, 0), "<=", 900)
add.constraint(lprec, c(0, 0, 0, 1, 1, 1, 0, 0, 0), "<=", 1200)
add.constraint(lprec, c(0, 0, 0, 0, 0, 0, 1, 1, 1), "<=", 750)
add.constraint(lprec, c(6, 6, 6, -5, -5, -5, 0, 0, 0), "=", 0)
add.constraint(lprec, c( 3, 3, 3, 0, 0, 0, -5, -5, -5), "=", 0)

#set.bounds(lprec, lower = c(0, 0, 0, 0, 0, 0, 0, 0, 0), columns = c(1, 2,3,4,5,6,7,8,9))

# To identify the variables and constraints, we can set variable names and name the constraints
RowNames <- c("CapCon1", "CapCon2", "CapCon3", "StoCon1", "StoCon2", "StoCon3", "SalCon1", "SalCon2", "SalCon3", "%C1", "%C2")
ColNames <- c("P1Large", "P1Medium", "P1Small", "P2Large", "P2Medium", "P2Small", "P3Large", "P3Medium", "P3Small")
dimnames(lprec) <- list(RowNames, ColNames)

lprec

write.lp(lprec, filename = "A2QMM.lp", type = "lp")
```

```{r}
solve(lprec)

get.objective(lprec)
get.variables(lprec)
```


```{r}

```


```{r}

```
